device = "eg.wz.schrank"
canid = 0x338
# canid = 0x10

[led.wand]
name = "Lampe auf dem Schrank"
port = 1
# default = 50

[led.salzlampe]
name = "Salzlampe"
port = 2
# default = 50

[led.lichterkette]
name = "Weihnachtslichterkette"
port = 3
# default = 30

# [led.spare]
# name = "Spare"
# port = 4

[rgb.rgb]
name = "Farbige Lichterkette"
port = 9

# 2 * motionsensor

[motionsensor.directiondoor]
name = "Schrank Richtung WZ Tür"
port = 0x10

[motionsensor.directionessz]
name = "Schrank Richtung Esszimmer"
port = 0x11


[am2302.temperature]
name = "Wohnzimmerschrank"
port = 0x20

[trigger.dingdong]
name = "DingDong Klingel"
port = 0x30


[dependencies]
libfiles = ["board.py", "boot.py", "button.py", "can.py", "cancodes.py", "cancommon.py",
    "canconf.py", "canerror.py", "canesp32.py", "canid.py", "caninfo.py", "irqio.py",
    "motionsensor.py", "net.py", "pwm.py", "pwmcode.py", "sensors.py",
    "rgb.py", "digiio.py"
]
