# code generated by   hidepw hc XXX SIoT XXX
b = bytearray((5, 5, 7, 11, 17, 19, 111, 110, 17, 123, 104, 127, 57, 63, 19, 227, 60, 13, 157, 37, 129, 200, 26, 60, 72, 170, 12, 45, 90, 197, 21, 41, 165, 239, 78, 233, 231, 224, 100, 92, 116, 91, 11, 119, 124, 116, 123, 121, 136, 131, 124, 7, 101, 144, 87, 146, 59, 108, 133, 136, 249, 55, 51, 194, 206, 2, 215, 117, 203, 87))

ni = b[0]

def _s(o):
    r = ''
    o += ni
    while True:
        o += 1
        c = b[o] - b[(o)%ni+1]
        #print('# Getting @{:2d}: {:3d} -> {:3d} {:3d} {}'.format(o, b[o], c, c & 0xff, chr(c&0xff)))
        if c == 0:
            return r, o-ni
        r = r+chr(c&0xff)

def s(n):
    a, b = _s(n)
    #print('#   GOT {} {}'.format(b, a))
    c, _ = _s(b)
    return a, c

if __name__ == '__main__':
    print('block is {} bytes'.format(len(b)))
    print(s(0))
    print(s(32))
