package main

// Obscure / hide credentials in the source code.
// This is by no means intended to be an encryption or similar. It will simply make your
// WLAN IPs and access codes unreadable.
// Just in case your ESP gets stolen (from your external XMas light show installation)
// If connected to USB it would be very easy to identify the passwords in the source files,
// even if the files have been compiled with mpy-cross - which you should do in any case
//
// The compiled files will make it at least much harder to get the password out of the source.
// You would need some debugging and slightly deeper knowledge.
//

// go run main.go    192.168.178.2   meinpasswort-1   10.10.4.2    deinpw-2
//
// go run main.go -m -o c.py iot-ssid iot-pw   alternate-ssid alternate-pw
//
// will generate a Python file where you can call
//
// import xx
//
// xx.i(0)  -> first IP as string (192.168.178.2)
// xx.s(4)  -> first PW as string (meinpasswort-1)
// xx.i(21) -> second IP as string
// xx.s(25) -> second PW

import (
	"bytes"
	"fmt"
	"log/slog"
	"math/rand"
	"os"
	"os/exec"
	"strings"

	"github.com/spf13/pflag"

	"github.com/fpunkt/cslog"
)

const blockSize = 32 // max size for 2 strings

var (
	offsets = []byte{5, 7, 11, 17, 19}
	//buffer  = strings.Builder{}
	buffer = bytes.Buffer{}
	//oindex  = 0
	verbose = 2

	currentPad = 1 + len(offsets)
)

func addbyte(b byte) {
	oindex := buffer.Len()
	table := byte((b + offsets[oindex%len(offsets)]) & 0xff)
	cslog.Trace("Adding byte", "pos", buffer.Len(), "byte", b, "table", table)
	buffer.WriteByte(table)
	//oindex++
}

func addstring(s string) {
	slog.Debug("Adding string", "str", s)
	for _, c := range s {
		addbyte(byte(c))
	}
	addbyte(0)
}

func pad() {
	currentPad += blockSize
	if buffer.Len() >= currentPad {
		cslog.Fatal("Strings to long, reduce size (change code)", "size", buffer.Len(), "maxsize", currentPad)
	}
	cslog.Trace("Padding bytes", "n", currentPad-buffer.Len())
	for buffer.Len() < currentPad {
		b := rand.Intn(255)
		buffer.WriteByte(byte(b))
	}
}

func decode(fname string) {
	mod := strings.TrimSuffix(fname, ".py")
	cmd := fmt.Sprintf("import %s; print(%s.s(0), %s.s(32))", mod, mod, mod)
	slog.Debug("Going to run python command", "cmd", cmd)
	out, err := exec.Command("python3", "-c", cmd).Output()
	if err != nil {
		cslog.Fatal("Cannot run python", "cmd", cmd, "error", err)
	}
	fmt.Println(string(out))
}

func main() {
	pflag.CountVarP(&verbose, "verbose", "v", "verbose messages")
	outputFile := pflag.StringP("output", "o", "", "Output file for generated python code")
	decodeFlag := pflag.BoolP("decode", "d", false, "Decode given python file")
	writeMain := pflag.BoolP("main", "m", false, "Create main-function for testing python code")
	pflag.Usage = func() {
		fmt.Println("hallo")
	}
	pflag.Parse()

	cslog.InitV(verbose)

	if *decodeFlag {
		mod := "c"
		if pflag.NArg() == 1 {
			mod = pflag.Arg(0)
		}
		decode(mod)
		return
	}

	buffer.WriteByte(byte(len(offsets)))
	for _, o := range offsets {
		buffer.WriteByte(o)
	}

	if pflag.NArg() == 0 {
		slog.Error("Need at least two arguments, use like hidepw  ssid-1 pw-1  ssid-2 pw-2")
		return
	}
	for i, arg := range pflag.Args() {
		//if isip(arg) {
		//	addip(arg)
		//	continue
		//}
		addstring(arg)
		if i%2 == 1 {
			pad()
		}
	}

	// write Python code

	fd := os.Stdout

	if *outputFile != "" {
		slog.Info("Writing Python outputfile", "file", *outputFile)
		f, err := os.Create(*outputFile)
		if err != nil {
			slog.Error("Cannot generate output file", "name", *outputFile, "error", err)
		}
		fd = f
		defer fd.Close()
	}

	//b := buffer.Bytes()
	//fmt.Printf("s = %q\n", buffer.Bytes())
	var generated, use []string
	for i, a := range pflag.Args() {
		if i%2 == 0 {
			generated = append(generated, a)
			use = append(use, fmt.Sprintf("# use     s(%d)   # %16s xxx", i/2, a))
		} else {
			generated = append(generated, "XXX")
		}
	}

	fmt.Fprint(fd, "# code generated by   hidepw ", strings.Join(generated, " "), "\n")

	fmt.Fprintf(fd, "b = bytearray((")
	comma := ""
	for _, b := range buffer.Bytes() {
		fmt.Fprintf(fd, "%s%d", comma, b)
		comma = ", "
	}
	fmt.Fprintf(fd, "))\n")
	//fmt.Printf("s = %b\n", buffer.Bytes())

	detab := func(s string) string { return strings.ReplaceAll(s, "\t", "    ") }

	// generate code
	fd.WriteString(detab(pyCode))
	if *writeMain {
		fd.WriteString(detab(mainCode))
	}

	fmt.Print("\n", strings.Join(use, "\n"), "\n")
}

const (
	pyCode = `
ni = b[0]

def _s(o):
	r = ''
	o += ni
	while True:
        o += 1
        c = b[o] - b[(o)%ni+1]
		#print('# Getting @{:2d}: {:3d} -> {:3d} {:3d} {}'.format(o, b[o], c, c & 0xff, chr(c&0xff)))
		if c == 0:
			return r, o-ni
		r = r+chr(c&0xff)

def s(n):
    a, b = _s(n)
	#print('#   GOT {} {}'.format(b, a))
	c, _ = _s(b)
	return a, c
`
	mainCode = `
if __name__ == '__main__':
    print('block is {} bytes'.format(len(b)))
    print(s(0))
    print(s(32))
`
)
