# code generated by   hidepw wifi XXX sentinel XXX
b = bytearray((5, 5, 7, 11, 17, 19, 126, 116, 119, 124, 5, 127, 131, 137, 19, 90, 23, 243, 27, 233, 181, 28, 107, 208, 141, 145, 46, 87, 241, 188, 47, 183, 74, 99, 135, 113, 176, 13, 132, 120, 115, 123, 116, 127, 120, 113, 7, 111, 115, 139, 105, 105, 131, 139, 70, 51, 53, 11, 208, 122, 155, 158, 30, 167, 95, 84, 15, 232, 60, 67))

ni = b[0]

def _s(o):
    r = ''
    o += ni
    while True:
        o += 1
        c = b[o] - b[(o)%ni+1]
        #print('# Getting @{:2d}: {:3d} -> {:3d} {:3d} {}'.format(o, b[o], c, c & 0xff, chr(c&0xff)))
        if c == 0:
            return r, o-ni
        r = r+chr(c&0xff)

def s(n):
    a, b = _s(n)
    #print('#   GOT {} {}'.format(b, a))
    c, _ = _s(b)
    return a, c

# use     s(0)   #             wifi xxx
# use     s(1)   #         sentinel xxx
