# DO NOT EDIT !! File automatically generated by "cantool header -g canconf.toml -l mpy"
"""
Constant file generated from canconf.toml
"""
if 0 == 1:
    # make pylint think that it knows about 'const' variable
    # pylint: disable=used-before-assignment, undefined-variable, self-assigning-variable
    const = lambda x: x

HARD_RESET                                         = const(  240) # 0x00f0

SOFT_RESET                                         = const(  241) # 0x00f1

# Ask device to respond with a ping request.
# Device is assumed to be down if ping is not received within a second.
#   Arg # 0: [period/[8, 16]] - requested ping period in seconds, MSB first
REQUEST_PING_FROM_DEVICE                           = const(  242) # 0x00f2

INDENTIFY                                          = const(  243) # 0x00f3

ENABLE_WATCHDOG                                    = const(  244) # 0x00f4

SEND_INFO                                          = const(  245) # 0x00f5

# This message is send [periodically] to the device if requested.
# Request via xxx command
# The device can use this to detect bus issues and trigger a watchdog if the message isn't been send
# periodically. This is a per-client (canid) message so the device can filter (ignore all other messages)
# and the system can keep a per-device period.
BUS_IS_ALIVE                                       = const(  246) # 0x00f6

# Turn debugging OFF if called with one arg == 0, otherwise turn debugging ON.
# Turning debuggin on/off means setting the board.DEBUG variable
DEBUG_ON_OFF                                       = const(  247) # 0x00f7

WLAN_CONNECT                                       = const(  250) # 0x00fa

WLAN_HOTSPOT                                       = const(  251) # 0x00fb

WLAN_STOP                                          = const(  252) # 0x00fc

WEBREPL_START                                      = const(  253) # 0x00fd

WEBREPL_STOP                                       = const(  254) # 0x00fe

SEND_FREEMEM                                       = const(  255) # 0x00ff

