# DO NOT EDIT !! File automatically generated by "cantool header -g -l mpy canconf.toml"
"""
Constant file generated from canconf.toml
"""
if 0 == 1:
    # make pylint think that it knows about 'const' variable
    # pylint: disable=used-before-assignment, undefined-variable, self-assigning-variable
    const = lambda x: x

HARD_RESET                                         = const(  240) # 0x00f0

SOFT_RESET                                         = const(  241) # 0x00f1

SEND_PING                                          = const(  242) # 0x00f2

INDENTIFY                                          = const(  243) # 0x00f3

ENABLE_WATCHDOG                                    = const(  244) # 0x00f4

WLAN_CONNECT                                       = const(  250) # 0x00fa

WLAN_HOTSPOT                                       = const(  251) # 0x00fb

WLAN_STOP                                          = const(  252) # 0x00fc

WEBREPL_START                                      = const(  253) # 0x00fd

WEBREPL_STOP                                       = const(  254) # 0x00fe

SEND_FREEMEM                                       = const(  255) # 0x00ff
