# Code generated by "cantool header -l py -g canconf.toml"; DO NOT EDIT.
"""
Constant file generated from canconf.toml
"""
if 0 == 1:
    # make pylint think that it knows about 'const' variable
    # pylint: disable=used-before-assignment, undefined-variable, self-assigning-variable
    const = lambda x: x

CONFIG_BEGIN                                       =   240 # 0x00f0

HARD_RESET                                         =   240 # 0x00f0

SOFT_RESET                                         =   241 # 0x00f1

SEND_PING                                          =   242 # 0x00f2

INDENTIFY                                          =   243 # 0x00f3

ENABLE_WATCHDOG = 244 # 0xf4

WLAN_CONNECT                                       =   250 # 0x00fa

WLAN_HOTSPOT                                       =   251 # 0x00fb

WLAN_STOP                                          =   252 # 0x00fc

WEBREPL_START                                      =   253 # 0x00fd

WEBREPL_STOP                                       =   254 # 0x00fe
