# Code generated by "cantool header -l py -g canerror.toml"; DO NOT EDIT.
"""
Constant file generated from canerror.toml
"""
if 0 == 1:
    # make pylint think that it knows about 'const' variable
    # pylint: disable=used-before-assignment, undefined-variable, self-assigning-variable
    const = const
# Internal error, more PWMs defined as allowed by array dimension on CAN device
TOO_MANY_PWMS                                      =    11 # 0x000b
TEST                                               =     1 # 0x0001
BAD_PARAMETER_VALUE                                =     4 # 0x0004
# Device ID is used more than once
MULTIPLE_USE_OF_DEVICE_ID                          =     4 # 0x0004
BAD_PWM_NUMBER                                     =     6 # 0x0006
UNKNOWN_SUBCOMMAND                                 =     7 # 0x0007
BAD_NUMBER_OF_PARAMETERS                           =     2 # 0x0002
FUNCTION_NOT_IMPLEMENTED                           =     9 # 0x0009
# special value used when indicating NO error (but 0 return value already reserved)
CAN_NO_ERROR                                       =   255 # 0x00ff
INTERNAL_ERROR                                     =     5 # 0x0005
UNKNOWN_CONFIG_COMMAND                             =    10 # 0x000a
# Too many devices
INTERNAL_TOO_MANY_DEVICES                          =     3 # 0x0003
CAN_UNKNOWN_COMMAND                                =     3 # 0x0003
