# DO NOT EDIT !! File automatically generated by "cantool header -l mpy -g canid.toml"
"""
Constant file generated from canid.toml
"""
if 0 == 1:
    # make pylint think that it knows about 'const' variable
    # pylint: disable=used-before-assignment, undefined-variable, self-assigning-variable
    const = lambda x: x

# Message sent when a button has been pressed
BUTTON_PRESSED                                     = const(  896) # 0x0380

SENSOR_MOTION                                      = const(  928) # 0x03a0

SENSOR_WINDOW                                      = const(  930) # 0x03a2

SENSOR_DOOR                                        = const(  932) # 0x03a4

SENSOR_LIGHTSWITCH_OVERRIDE                        = const(  934) # 0x03a6

SENSOR_DOORBELL_PUSHED                             = const(  936) # 0x03a8

# CanidActuatorMessage is sent by acutators (e.g. blinds control)
# Payload is sender/16 CODE/8 motorid/8  percent/8 count/16 predef/8
# Where CODE/8 is
# - 0x00:   motor stopped after reaching position
# - 0x01:   motor stopped error code 0x01 (error codes range from 0x01 to 0x0f)
# - 0x0f:   motor stopped error code 0x0f (error codes range from 0x01 to 0x0f)
# - 0x10:   motor started moving forward/down/clockwise to position
# - 0x11:   motor started moving backward/up to position
# - 0x20:   motor moving forward, status current position
# - 0x21:   motor moving backward, status current position
# - 0x30:   motor not moving but sending current position (send status from time to time)
# Percent or predef can be 0xff if N/A
SENSOR_ACTUATOR                                    = const(  938) # 0x03aa

SENSOR_DIGITAL_INPUT                               = const(  955) # 0x03bb

DIGITAL_INPUT                                      = const(  960) # 0x03c0

# PWM messages from CAN devices before 08/2020. Use pwm_value instead.
PWM_VALUE_2019                                     = const(  962) # 0x03c2

POWER_ON                                           = const(  964) # 0x03c4

# Send device information. Same as power on.
IDENTIFY                                           = const(  965) # 0x03c5

# Send WLAN IP of the connected device
WLAN_CONNECTED                                     = const(  966) # 0x03c6

# The generic_device ID is used debugging only (virtual function not overloaded)
GENERIC_DEVICE                                     = const(  967) # 0x03c7

# Reports power level for given PWM
#   Arg # 0: senderid/16
#   Arg # 1: portid/8
#   Arg # 2: PWM raw value/16 (0..2^n-1 where n is the PWM resolution in bits)
#   Arg # 3: PWM normalized value/16 from 0..0xffff
PWM_VALUE                                          = const(  968) # 0x03c8

# Reports number of configered PWMs and number of PWMs that currently have intensity != 0
PWM_POWER_CONFIG                                   = const(  969) # 0x03c9

# Send CANID/16 and the free memory/32 as payload
MEMORY_STATUS                                      = const(  970) # 0x03ca

# Report RGB values (12 bit resolution): sender, r/8, g/8, b/8 plus lower 4bit from rgb
#   Arg # 0: senderid/16
#   Arg # 1: portid/8
#   Arg # 2: red>>4/8 is the upper eight bit from the 12 bit value
#   Arg # 3: green>>4/8 is the upper eight bit from the 12 bit value
#   Arg # 4: blue>>4/8 is the upper eight bit from the 12 bit value
#   Arg # 5: red&0xf/8 lower4 bit from red -> r & 0x0f
#   Arg # 6: green and blue & 0xf /8, lower 4 bits --> (g & 0x0f) << 4 | (b & 0x0f)
PWM_RGB_VALUE                                      = const(  971) # 0x03cb

# Send H/W information like CPU type, Board version, Pheriperals
CONFIG_INFO                                        = const(  972) # 0x03cc

# PWM info packet, things like resolution and others
#   Arg # 0: senderid/16
#   Arg # 1: portid/8
#   Arg # 2: what/8: what is contained in this packet
#   Arg # 3: w=0 4/8  native resolution
#   Arg # 4: w=0 5/16 current value in native units/16
PWM_INFO                                           = const(  973) # 0x03cd

DATALOGGER_HUMIDITY_SENSOR                         = const( 1776) # 0x06f0

DATALOGGER_AM2302                                  = const( 1777) # 0x06f1

DATALOGGER_TEMPERATURE_SENSOR                      = const( 1778) # 0x06f2

DATALOGGER_RAW_ADC_VALUES_16                       = const( 1780) # 0x06f4

DATALOGGER_RAW_ADC_VALUES_8                        = const( 1781) # 0x06f5

# Report readings from brightness sensors (8-bit values): 0 is dark, 0xff is very bright
DATALOGGER_BRIGHTNESS_SENSOR_8                     = const( 1782) # 0x06f6

DATALOGGER_USER_REQUEST                            = const( 1784) # 0x06f8

DATALOGGER_POWERPLUG                               = const( 1786) # 0x06fa

# Error message on the CAN bus
ERROR_MESSAGE                                      = const( 1888) # 0x0760

# Info message, like WLAN connected, etc
INFO_MESSAGE                                       = const( 1904) # 0x0770

CANCONF_REPLY                                      = const( 1961) # 0x07a9

# Send CANID/16 pingcounter/16. Most devices send a ping every few seconds.
# Some smart software could use PING messages to
# detect problems with a device or with the bus (and hand over to a redundant unit or send an email).
# In your device application code, your should use the ``PING()`` macro to trigger ping messages.
PING_MESSAGE                                       = const( 2016) # 0x07e0

# Send CANID/16 and freestyle debug message.
# The Debug messages can be switched on / off via CAN command.
DEBUG_MESSAGE                                      = const( 2024) # 0x07e8

