# DO NOT EDIT !! File automatically generated by "cantool header -l py -g pwmcode.toml"
"""
Constant file generated from pwmcode.toml
"""
if 0 == 1:
    # make pylint think that it knows about 'const' variable
    # pylint: disable=used-before-assignment, undefined-variable, self-assigning-variable
    const = lambda x: x

# Turn on PWM with last intensity
ON                                                 =    22 # 0x0016

# Turn off PWM
OFF                                                =    23 # 0x0017

# Toggle PWM
TOGGLE                                             =    24 # 0x0018

# Set PWM to given intensity
SET_INTENSITY16                                    =    26 # 0x001a

# Request the PWM configuration. Sends a pwm_power_config if no argument is provided or a pwm_value packet
#   Arg # 0: [portid/8]
REQUEST_CONFIG                                     =    27 # 0x001b

# Configure PWM. See configure_ ... entries for more details
#   Arg # 0: configcommand/8
#   Arg # 1: [portid/8]
#   Arg # 2: [param/8]
CONFIGURE                                          =    28 # 0x001c

# Set RGB values (three independend PWMs). All values are 16 bit, e.g. 0..0xffff
#   Arg # 0: r/16
#   Arg # 1: g/16
#   Arg # 2: b/16
RGB                                                =    29 # 0x001d

# set number of dimsteps/8, default is 50
CONFIGURE_DIMSTEPS                                 =     4 # 0x0004

# set dimintervall/8 (milliseconds between dimsteps), default is 5 ms
CONFIGURE_DIMINTERVALL                             =     5 # 0x0005

# Configure as binary device
CONFIGURE_BINARY                                   =     6 # 0x0006

# Configure what toggle should do with PWM Lists where some
# PWM are on others are off.
# If Arg is 0 toggle will turn all off if at least on is on
# If Arg is 1 toggle will turn all on if not all were off
#
#   Arg # 0: pwmid/8
#   Arg # 1: mode/8
CONFIGURE_TOGGLE                                   =     7 # 0x0007
