# Code generated by "cantool header -l py -g pwmcode.toml"; DO NOT EDIT.
"""
Constant file generated from pwmcode.toml
"""
if 0 == 1:
    # make pylint think that it knows about 'const' variable
    # pylint: disable=used-before-assignment, undefined-variable, self-assigning-variable
    const = const

# Turn on PWM with last intensity
ON                                                 =    22 # 0x0016

# Turn off PWM
OFF                                                =    23 # 0x0017

# Set PWM to given intensity
SET_INTENSITY                                      =    26 # 0x001a

# Request the PWM configuration. Sends a pwm_power_config if no argument is provided or a pwm_value packet
#   Arg # 0: [portid/8]
REQUEST_CONFIG                                     =    27 # 0x001b

# set number of dimsteps/8, default is 50
CONFIGURE_DIMSTEPS                                 =     4 # 0x0004

# set dimintervall/8 (milliseconds between dimsteps), default is 5 ms
CONFIGURE_DIMINTERVALL                             =     5 # 0x0005

# Configure as binary device
CONFIGURE_BINARY                                   =     6 # 0x0006
