# DO NOT EDIT !! File automatically generated by "cantool header -l py -g pwmcode.toml"

# Turn on PWM with last intensity
ON                                                 =    22 # 0x0016

# Turn off PWM
OFF                                                =    23 # 0x0017

# Toggle PWM
TOGGLE                                             =    24 # 0x0018

# Set PWM to given intensity in native units, e.g. 0..1023 for a 10 bit PWM
#   Arg # 0: portid/8
#   Arg # 1: value/16
SET_INTENSITY_NATIVE                               =    25 # 0x0019

# Set PWM to given intensity using values from 0..0xffff
#   Arg # 0: portid/8
#   Arg # 1: value/16
SET_INTENSITY16                                    =    26 # 0x001a

# PWM information and configuration command.
# Sends a pwm_power_config packet if no argument is provided, otherwise a pwm_info_packet
#   Arg # 0: [portid/8] - if missing return pwm_power_config: #ports and #ports with power > 0
#   Arg # 1: command/8 - 1: portconfig, return resolution and current value for port
#   Arg # 2: /8 - 2: configure PWM ---
CONFIG                                             =    27 # 0x001b

# Set RGB values (three independend PWMs). Values are in native units, e.g. 10bit -> 0..1023 (H/W dependend)
#   Arg # 0: portid/8
#   Arg # 1: r/16
#   Arg # 2: g/16
#   Arg # 3: b/16
SET_RGBNATIVE                                      =    28 # 0x001c

# Set RGB values (three independend PWMs). Values are in native units, e.g. 10bit -> 0..1023 (H/W dependend)
#   Arg # 0: portid/8
#   Arg # 1: r/16
#   Arg # 2: g/16
#   Arg # 3: b/16
DIM_RGBNATIVE                                      =    29 # 0x001d

# Set RGB values (three independend PWMs). All values are 16 bit, e.g. 0..0xffff
#   Arg # 0: portid/8
#   Arg # 1: r/16
#   Arg # 2: g/16
#   Arg # 3: b/16
SET_RGB16                                          =    30 # 0x001e

# Set RGB values (three independend PWMs). All values are 16 bit, e.g. 0..0xffff
#   Arg # 0: portid/8
#   Arg # 1: r/16
#   Arg # 2: g/16
#   Arg # 3: b/16
DIM_RGB16                                          =    31 # 0x001f
