device = "eg.wz.roof"
canid = 0x358
room = "Wohnzimmer"

# [led.mid]
# name = "Decke (Mitte)"
# port = 2
#
# [led.couch]
# name = "Decke (Couch)"
# port = 1
#
# [led.win]
# name = "Decke (Fenster)"
# port = 3

[led.spottv]
name = "Spot TV"
port = 1

[led.spotwz]
name = "Spot WZ"
port = 2

[led.spotcenter]
name = "Spot Center"
port = 3

[led.spotwand]
name = "Spot Wand"
port = 4

[led.spotfenster]
name = "Spot Fenster"
port = 5

[led.xmas]
name = "Weihnachtsstern"
port = 6 # 5

[led.spare]
name = "Spare"
port = 7 # 6

[led.tvlight]
name = "Fernsehlampe"
port = 8 # 4

[led.candle]
name = "1900 K LED Streifen"
port = 10 # 7

[led.entrance]
name = "Wohnzimmertür (2400 K)"
port = 11 # 8


[button.left]
port = 0x21

[button.right]
port = 0x20

