device = "eg.kueche.fridge"
canid = 0x350
room = "Küche"

[led.arbeitsplattewarm]
name = "Arbeitsplatte (warm)"
port = 3 # 0

[led.arbeitsplattecold]
name = "Arbeitsplatte (kalt)"
port = 4 # 1

[led.hoodwarm]
name = "Abzugshaube (warm)"
port = 2 # 2

[led.hoodcold]
name = "Abzugshaube (kalt)"
port = 8 # 3

[led.notconnected1]
name = "NC"
port = 5

[led.window]
name = "Kaffeemühle"
port = 1 # 4

[led.corner]
name = "Eckschrank"
port = 6

[led.sink]
name = "Spüle"
port = 7

[button.right]
port = 0x10

[button.center]
port = 0x11

[button.left]
port = 0x12

[am2302.kueche]
port = 0x30
name = "Küche"

[motion.fridge]
name = "Durchgang"
port = 0x20

[motion.corner]
name = "Ecke"
port = 0x21
